"""
Tool execution command (launches the bash scripts).
"""
import os
import logging

from bench.utils.functions import *
from bench.utils.tool_commands import load_tool_configs

logger = logging.getLogger(__name__)


def run_execute_tools(input_dir, skip_tools='', only_tools=None, debug=False):
    """
    Core tool execution function.
    
    This function executes the bash scripts generated by generate_scripts,
    running each alignment tool and collecting output files.
    
    Note: This function only executes pre-generated scripts, so it doesn't
    need threads/max_runs/warmups parameters - those are baked into the scripts.
    
    Args:
        input_dir: Directory containing scripts and simulated data
        skip_tools: Comma-separated list of tools to skip
        only_tools: Comma-separated list of tools to run (overrides skip_tools)
        debug: If True, run commands directly without hyperfine for better error messages
    """
    logger.debug(f"Executing tools from {input_dir}")
    
    # Ensure directories exist
    if not os.path.exists(input_dir):
        logger.error(f"Input directory {input_dir} does not exist")
        raise FileNotFoundError(f"Input directory {input_dir} does not exist")
    
    # Create necessary subdirectories, just in case
    os.makedirs(f"{input_dir}/raw_outputs", exist_ok=True)
    os.makedirs(f"{input_dir}/bash_scripts", exist_ok=True)
    logger.debug("Ensured output directories exist")
    
    # Load tool configurations (minimal - just to get tool names and script paths)
    # We use dummy values since we're only executing pre-generated scripts
    logger.debug("Loading tool configurations...")
    tools = load_tool_configs(
        results_dir=input_dir,
        threads=1,  # Not used when executing scripts
        contigs_file=None,
        spacers_file=None
    )
    logger.debug(f"Loaded {len(tools)} tool configurations")
    
    # Filter tools based on skip_tools
    if skip_tools:
        logger.debug(f"Skipping tools: {skip_tools}")
        skip_list = skip_tools.split(",")
        tools = {k: v for k, v in tools.items() if k not in skip_list}
        logger.debug(f"Remaining tools after skip: {len(tools)}")
    
    # Filter tools based on only_tools
    if only_tools:
        logger.debug(f"Only running tools: {only_tools}")
        only_list = only_tools.split(",")
        tools = {k: v for k, v in tools.items() if k in only_list}
        logger.debug(f"Tools to run: {len(tools)}")
    
    # Run tools and collect results
    logger.debug(f"Executing {len(tools)} tools...")
    if debug:
        logger.debug("Debug mode enabled - running commands directly without hyperfine")
    try:
        run_tools(tools, input_dir, debug=debug)
        logger.debug("All tools executed successfully")
    except Exception as e:
        logger.error(f"Tool execution failed: {e}", exc_info=True)
        raise
